phishing document
Redback-Operations/redback-documentation pull request #90
Opened 2024-08-20 03:11 UTC by buvan008

2024-08-20 07:08 UTC, SassafrasAU requested changes
Heya,

Looks good for the most part, just two small issues

- Please add the following to the top of the document, with x being the number of documents (including this one) in the folder it is in
```
---
sidebar_position: x
---
```

- I'm also not entirely sure the purple team usecases folder is the right spot for this. I could argue that there might even be a need for a new "Cyber Concepts" folder given a surge in these types of reports. @Deamauni1090 / @ben-AI-cybersec may be able to comment more on this

2024-08-22 08:36 UTC, ben-AI-cybersec commented
How about we change the purple team dir to exclusively red team, this would fit there. We already have an existing blue team directory we can move any blue stuff out of the purple team section.

2024-09-07 14:35 UTC, SassafrasAU approved these changes

2024-09-07 14:35 UTC, merged

2024-09-07 14:39 UTC, SassafrasAU commented
For your awareness @buvan008, the phshing.md doc had incorrect file types on the images (png rather than jpg). I would suggest renaming your images to something meaningful rather than just "image-x"